### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by taqyon** [atls/jobs#5]
## 1. Статусы вакансии
Какие бывают статусы вакансии? 

## 2. Действия которые можно совершать с вакансией
Какие? 

## 3. При создании вакансии, скиллы будут подтягиваться из организации/подразделения? 
Или можно указывать их при создании вакансии, тем самым, наполняя пул скиллов организации. Не могу понять какая здесь зависимость.

**Comment by taqyon** [comment]
in progress

**Comment by TorinAsakura** [comment]
### Job Statuses
- Draft
- Worked
- Closed

### Actions
- создать
- перевести в черновик
- открыть
- закрыть

3. Да
