### ISSUE TITLE
Вопрос: Стоит ли вводить отдельный статус для вакансии — платёжный статус

### ISSUE THREAD

**Issue by taqyon** [atls/jobs#8]
Исходя из сценариев оплаты и флоу работы с вакансией назрел такой вопрос. Стоит ли вводить отдельный статус для вакансии — платёжный статус? 

Например: 

- Не оплачена
- Оплачена частично
- Оплачена

## Зачем? 

Так как у нас предполагается оплата вакансии в два этапа: 
1. при оплате размещения 
2. при закрытии вакансии (на этапе — Соискатель принимает оффер)

То логично было бы отслеживать на протяжении жизни вакансии её платежный статус. 

В случае, если работодатель не оплачивает вторую половину по какой-то причине. Мы можем, например, заблокировать создание новой вакансии пока прошлая не будет оплачена. Или ввести лимиты и тд. и тп. 

Что думаешь?

**Comment by TorinAsakura** [comment]
Стоит
